# Generated by Django 3.2.4 on 2021-07-03 03:06

from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fazenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da fazenda.', max_length=50)),
                ('municipio', models.CharField(help_text='Município.', max_length=100)),
                ('estado', models.CharField(help_text='Estado.', max_length=5)),
                ('area_total', models.IntegerField(help_text='Área total (Hectare).')),
                ('area_aberta', models.IntegerField(help_text='Área aberta (Hectare).')),
                ('cultura', models.CharField(help_text='Cultura.', max_length=255)),
                ('infra', models.CharField(help_text='Características de infraestrutura.', max_length=255)),
                ('maquinario', models.CharField(help_text='Maquinário (Trator, caminhão, carro e etc...)', max_length=255)),
                ('local_ref', models.CharField(help_text='Referências de localização.', max_length=255)),
                ('coordenada', models.CharField(help_text='Coordenadas.', max_length=100)),
                ('valor_currency', djmoney.models.fields.CurrencyField(choices=[('BRL', 'Brazilian Real'), ('USD', 'US Dollar')], default='BRL', editable=False, max_length=3)),
                ('valor', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='BRL', max_digits=14)),
                ('obs', models.TextField(help_text='Observações.', max_length=3000)),
                ('encaminhado', models.CharField(help_text='Encaminhado por.', max_length=50)),
                ('oferta', models.CharField(help_text='Ofertada para.', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FazendaMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='imagens/')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='audios/')),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.fazenda')),
            ],
        ),
    ]
